name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and run with Docker Compose
        run: |
          docker compose up -d --build
          docker compose ps

      - name: Wait for services
        run: |
          echo "⏳ Waiting for services to start..."
          sleep 10

      - name: Health check NGINX
        run: |
          curl -f http://localhost:80 || (docker compose logs && exit 1)

      - name: Shut down
        if: always()
        run: docker compose down
